development:
  adapter: postgresql
  encoding: unicode
  database: baasje_development
  host: localhost
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: baasje_test
  host: localhost
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: baasje
  host: localhost
  pool: 5
  username: postgres
  password: